import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){if(testInfo.project.name==='webkit-tablet'){const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0});expect(response.status()).toBe(303);const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??'');expect(match?.[1]).toBeTruthy();const url=new URL(baseUrl);await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]);return;}await page.goto('/login/');await page.getByLabel('Usuario').fill(username);await page.getByLabel('Contraseña').fill(password);await page.getByLabel('Contraseña').press('Enter');await expect(page).toHaveURL(`${baseUrl}/`);}

test('F6 U4 overview gates advanced independence through P6',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-4/');await expect(page.getByRole('heading',{level:1,name:'Independencia funcional avanzada: capas con propósito'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/H4 FUNCIONAL/i)).toBeVisible();await expect(a.getByText(/C2 FUNCIONAL/i)).toBeVisible();await expect(a.getByText(/ruta de consolidación/i)).toBeVisible();});

test('F6 U4 L1 diagnoses before adding complexity',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-4/verificar-p6-y-localizar-el-cuello-de-botella/');await expect(page.getByRole('heading',{level:1,name:'Verificar P6 y localizar el cuello de botella'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByRole('heading',{name:'TEMPORAL'})).toBeVisible();await expect(a.getByRole('heading',{name:'MOTOR'})).toBeVisible();});

test('F6 U4 L4 returns coordination systems to music',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-4/del-sistema-al-groove-comping-textura-o-repertorio/');await expect(page.getByRole('heading',{level:1,name:'Del sistema al groove, comping, textura o repertorio'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/FUNCIÓN MUSICAL → CUELLO DE BOTELLA → EJERCICIO SELECCIONADO/i)).toBeVisible();await expect(a.getByText(/no reproduce ejercicios protegidos/i)).toBeVisible();});

test('F6 U4 checkpoint preserves boundaries with phase 7',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-4/checkpoint-independencia-funcional/');await expect(page.getByRole('heading',{level:1,name:'Checkpoint — Independencia funcional'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/polirritmia profunda/i)).toBeVisible();await expect(a.getByText(/modulación métrica/i)).toBeVisible();await expect(a.getByText(/Hito 7/i)).toBeVisible();await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible();});
