import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }

test('F6 U3 overview deepens chart reading into prioritization',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-3/');await expect(page.getByRole('heading',{level:1,name:'Charts densos, navegación y decisión'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/TIEMPO → FORMA → CUE\/ENTRADA → FIGURE → DETALLE/i)).toBeVisible();await expect(a.getByText(/En Fase 5 el objetivo era demostrar que podías/i)).toBeVisible();});

test('F6 U3 L3 distinguishes cues from mandatory drum hits',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-3/figures-cues-y-opciones-de-interpretacion/');await expect(page.getByRole('heading',{level:1,name:'Figures, cues y opciones de interpretación'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByRole('heading',{name:'Cue no significa «toca esto»'})).toBeVisible();await expect(a.getByRole('heading',{name:'Ejercicio original creado para este curso'})).toBeVisible();});

test('F6 U3 L4 trains recovery rather than stopping on local errors',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-3/perder-detalle-sin-perder-la-pieza/');await expect(page.getByRole('heading',{level:1,name:'Perder detalle sin perder la pieza'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/DETECTAR PÉRDIDA → SIMPLIFICAR → RECUPERAR PULSO/i)).toBeVisible();});

test('F6 U3 Checkpoint 6B preserves explicit boundaries',async({page},testInfo)=>{await login(page,testInfo);await page.goto('/bateria/fase-6-unidad-3/checkpoint-navegacion-y-decision/');await expect(page.getByRole('heading',{level:1,name:'Checkpoint 6B — Navegación y decisión'})).toBeVisible();const a=page.locator('article.course-article');await expect(a.getByText(/NAVEGAR UN CHART DE DIFICULTAD ADECUADA/i)).toBeVisible();await expect(a.getByText(/sight-reading profesional/i)).toBeVisible();await expect(a.getByText(/Hito 7/i)).toBeVisible();await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible();});
