import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }
async function scoreReady(page:Page){ const score=page.locator('article.course-article [data-notation-score]'); await expect(score).toHaveCount(1); await expect(score.locator('.course-score__status')).toHaveText('Partitura renderizada',{timeout:20_000}); await expect(score.getByRole('button',{name:'Reproducir partitura'})).toBeEnabled(); }

test('F5 U7 overview exposes space and anti-caricature boundaries', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-7/'); await expect(page.getByRole('heading',{level:1,name:'Espacio, offbeat y control de textura'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/ESPACIO ≠ AUSENCIA DE PULSO/i)).toBeVisible(); await expect(a.getByText(/Pieza B conserva su identidad shuffle/i)).toBeVisible(); });

test('F5 U7 L2 renders original one-drop/steppers model', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-7/one-drop-funcion/'); await expect(page.getByRole('heading',{level:1,name:'One-drop: función y espacio, no plantilla'})).toBeVisible(); await scoreReady(page); await expect(page.locator('article.course-article').getByText(/MODELO PEDAGÓGICO ≠ PATRÓN OFICIAL/i)).toBeVisible(); });

test('F5 U7 L4 protects Piece B shuffle identity', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-7/textura-recuperacion-pieza-b/'); await expect(page.getByRole('heading',{level:1,name:'Textura y recuperación: dejar espacio sin borrar el estilo'})).toBeVisible(); await expect(page.locator('article.course-article').getByText(/NO CONVIERTAS PIEZA B EN REGGAE/i)).toBeVisible(); });
