import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
const pieceCUrl='/bateria/fase-5-unidad-11/pieza-c-forma-primer-mapa/'; const metronomeStorageKey='aprendo-metronome-settings';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }
async function seedMetronomeBpm(page:Page,bpm:number){ await page.addInitScript(({key,value})=>{ localStorage.setItem(key,JSON.stringify({bpm:value})); },{key:metronomeStorageKey,value:bpm}); }
async function scoreReady(page:Page){ const score=page.locator('article.course-article [data-notation-score]'); await expect(score).toHaveCount(1); await expect(score.locator('.course-score__status')).toHaveText('Partitura renderizada',{timeout:20_000}); await expect(score.locator('.course-score__play')).toBeEnabled(); return score; }
async function setBpm(page:Page,value:number){ const bpm=page.locator('[data-metronome] [data-bpm]'); await bpm.evaluate((input,next)=>{ const element=input as HTMLInputElement; element.value=String(next); element.dispatchEvent(new Event('change',{bubbles:true})); },value); await expect(bpm).toHaveValue(String(value)); }

test('F5 U11 overview defines Piece C and hybrid-learning priority', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/'); await expect(page.getByRole('heading',{level:1,name:'Repertorio C y simulación de sesión'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/NINGUNA FUENTE ES “LA MÚSICA ENTERA”/i)).toBeVisible(); await expect(a.getByText(/INTRO 4 → A 8 → B 8 → A' 8 → OUTRO 4/i)).toBeVisible(); });

test('F5 U11 L1 Caso A: primera reproducción adopta el tempo recomendado sin arrancar el metrónomo', async({page},testInfo)=>{ await login(page,testInfo); await seedMetronomeBpm(page,90); await page.goto(pieceCUrl); await expect(page.getByRole('heading',{level:1,name:'Pieza C: escucha, forma y primer mapa'})).toBeVisible(); const score=await scoreReady(page); const a=page.locator('article.course-article'); await expect(a.getByText(/ESCUCHAR PRIMERO ≠ ADIVINAR TODO/i)).toBeVisible(); await expect(a.getByText(/Total: 32 compases de 4\/4/i)).toBeVisible(); const bpm=page.locator('[data-metronome] [data-bpm]'); const metronomePlay=page.locator('[data-metronome] [data-play]'); const scorePlay=score.locator('.course-score__play'); await expect(score).toHaveAttribute('data-recommended-bpm','120'); await expect(score.getByText('Tempo recomendado: 120 BPM')).toBeVisible(); await expect(bpm).toHaveValue('90'); await expect(metronomePlay).toHaveAttribute('aria-pressed','false'); await scorePlay.click(); await expect(bpm).toHaveValue('120'); await expect(metronomePlay).toHaveAttribute('aria-pressed','false'); await expect(scorePlay).toHaveAttribute('aria-pressed','true',{timeout:10_000}); });

test('F5 U11 L1 Caso B: un BPM elegido antes del primer Play prevalece sobre el recomendado', async({page},testInfo)=>{ await login(page,testInfo); await seedMetronomeBpm(page,90); await page.goto(pieceCUrl); const score=await scoreReady(page); const bpm=page.locator('[data-metronome] [data-bpm]'); const metronomePlay=page.locator('[data-metronome] [data-play]'); const scorePlay=score.locator('.course-score__play'); await setBpm(page,70); await scorePlay.click(); await expect(bpm).toHaveValue('70'); await expect(metronomePlay).toHaveAttribute('aria-pressed','false'); await expect(scorePlay).toHaveAttribute('aria-pressed','true',{timeout:10_000}); });

test('F5 U11 L1 Caso C: cambiar BPM después de reproducir no restaura el recomendado', async({page},testInfo)=>{ await login(page,testInfo); await seedMetronomeBpm(page,90); await page.goto(pieceCUrl); const score=await scoreReady(page); const bpm=page.locator('[data-metronome] [data-bpm]'); const metronomePlay=page.locator('[data-metronome] [data-play]'); const scorePlay=score.locator('.course-score__play'); await scorePlay.click(); await expect(bpm).toHaveValue('120'); await expect(scorePlay).toHaveAttribute('aria-pressed','true',{timeout:10_000}); await scorePlay.click(); await expect(scorePlay).toHaveAttribute('aria-pressed','false'); await setBpm(page,90); await scorePlay.click(); await expect(bpm).toHaveValue('90'); await expect(metronomePlay).toHaveAttribute('aria-pressed','false'); await expect(scorePlay).toHaveAttribute('aria-pressed','true',{timeout:10_000}); });

test('F5 U11 L1 Caso D: Restablecer recupera el recomendado sin iniciar el metrónomo ni la partitura', async({page},testInfo)=>{ await login(page,testInfo); await seedMetronomeBpm(page,75); await page.goto(pieceCUrl); const score=await scoreReady(page); const bpm=page.locator('[data-metronome] [data-bpm]'); const metronomePlay=page.locator('[data-metronome] [data-play]'); const scorePlay=score.locator('.course-score__play'); const reset=score.getByRole('button',{name:'Restablecer tempo recomendado de la partitura'}); await expect(bpm).toHaveValue('75'); await expect(scorePlay).toHaveAttribute('aria-pressed','false'); await reset.click(); await expect(bpm).toHaveValue('120'); await expect(metronomePlay).toHaveAttribute('aria-pressed','false'); await expect(scorePlay).toHaveAttribute('aria-pressed','false'); });

test('F5 U11 L3 treats partial information as prepared session work', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/simulacion-sesion-informacion-parcial/'); await expect(page.getByRole('heading',{level:1,name:'Simulación de sesión: responder con información parcial'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/INFORMACIÓN PARCIAL ≠ IMPROVISACIÓN A CIEGAS/i)).toBeVisible(); await expect(a.getByText(/TIEMPO → FORMA → ENTRADA\/CUE → DINÁMICA → GROOVE → DETALLE/i)).toBeVisible(); });

test('F5 U11 Checkpoint 5D certifies I3 functional without claiming Hito 6', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/i3-funcional/'); await expect(page.getByRole('heading',{level:1,name:'Checkpoint 5D — I3 COMPETENTE/FUNCIONAL'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/I3 COMPETENTE\/FUNCIONAL: aprende una pieza adecuada combinando escucha, lectura, memoria y análisis/i)).toBeVisible(); await expect(a.getByText(/Hito 6/i).first()).toBeVisible(); await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible(); });
