import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }
async function scoreReady(page:Page){ const score=page.locator('article.course-article [data-notation-score]'); await expect(score).toHaveCount(1); await expect(score.locator('.course-score__status')).toHaveText('Partitura renderizada',{timeout:20_000}); await expect(score.getByRole('button',{name:'Reproducir partitura'})).toBeEnabled(); }

test('F5 U11 overview defines Piece C and hybrid-learning priority', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/'); await expect(page.getByRole('heading',{level:1,name:'Repertorio C y simulación de sesión'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/NINGUNA FUENTE ES “LA MÚSICA ENTERA”/i)).toBeVisible(); await expect(a.getByText(/INTRO 4 → A 8 → B 8 → A' 8 → OUTRO 4/i)).toBeVisible(); });

test('F5 U11 L1 renders the 32-bar original formal reference', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/pieza-c-forma-primer-mapa/'); await expect(page.getByRole('heading',{level:1,name:'Pieza C: escucha, forma y primer mapa'})).toBeVisible(); await scoreReady(page); const a=page.locator('article.course-article'); await expect(a.getByText(/ESCUCHAR PRIMERO ≠ ADIVINAR TODO/i)).toBeVisible(); await expect(a.getByText(/Total: 32 compases de 4\/4/i)).toBeVisible(); });

test('F5 U11 L3 treats partial information as prepared session work', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/simulacion-sesion-informacion-parcial/'); await expect(page.getByRole('heading',{level:1,name:'Simulación de sesión: responder con información parcial'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/INFORMACIÓN PARCIAL ≠ IMPROVISACIÓN A CIEGAS/i)).toBeVisible(); await expect(a.getByText(/TIEMPO → FORMA → ENTRADA\/CUE → DINÁMICA → GROOVE → DETALLE/i)).toBeVisible(); });

test('F5 U11 Checkpoint 5D certifies I3 functional without claiming Hito 6', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-11/i3-funcional/'); await expect(page.getByRole('heading',{level:1,name:'Checkpoint 5D — I3 COMPETENTE/FUNCIONAL'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/I3 COMPETENTE\/FUNCIONAL: aprende una pieza adecuada combinando escucha, lectura, memoria y análisis/i)).toBeVisible(); await expect(a.getByText(/Hito 6/i).first()).toBeVisible(); await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible(); });
