import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }

test('F5 U9 overview protects provenance and rejects generic Latin', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-9/'); await expect(page.getByRole('heading',{level:1,name:'Brazilian / Afro-Cuban / Latin: capas con procedencia'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/BRAZILIAN ≠ AFRO-CUBAN ≠ “LATIN GENÉRICO”/i)).toBeVisible(); await expect(a.getByText(/Por qué no hay una partitura local “latina”/i)).toBeVisible(); });

test('F5 U9 L2 keeps samba layer lab explicitly non-authentic', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-9/samba-capas-kit/'); await expect(page.getByRole('heading',{level:1,name:'Samba: del conjunto al kit sin fingir equivalencia'})).toBeVisible(); await expect(page.locator('article.course-article').getByText(/LABORATORIO DE CAPAS ≠ GROOVE DE SAMBA/i)).toBeVisible(); });

test('F5 U9 L3 teaches clave orientation from verified external source', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-9/clave-capas-afrocubanas/'); await expect(page.getByRole('heading',{level:1,name:'Clave y capas afro-cubanas: orientación antes que independencia'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/CLAVE ≠ ADORNO RÍTMICO/i)).toBeVisible(); await expect(a.getByText(/Aprendo no reconstruye aquí la partitura/i)).toBeVisible(); });

test('F5 U9 L4 compares traditions without hybridizing them', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-9/transferencia-comparada/'); await expect(page.getByRole('heading',{level:1,name:'Transferencia comparada: cambiar de tradición sin mezclarla'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/TRANSFERIR ≠ MEZCLAR/i)).toBeVisible(); await expect(a.getByText(/Brazilian termina — Afro-Cuban empieza/i)).toBeVisible(); });
