import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }

test('F6 U2 overview presents transcription as hierarchical and uncertainty-aware', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-6-unidad-2/'); await expect(page.getByRole('heading',{level:1,name:'Transcripción útil, escucha jerárquica e incertidumbre'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/PULSO → FORMA → MÉTRICA\/SUBDIVISIÓN → FUNCIÓN DE GROOVE/i)).toBeVisible(); await expect(a.getByText(/HECHO VERIFICADO/i).first()).toBeVisible(); await expect(a.getByText(/Una reconstrucción propia/i)).toBeVisible(); });

test('F6 U2 L3 keeps sticking and uncertain detail epistemically honest', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-6-unidad-2/articulacion-dinamica-y-grados-de-certeza/'); await expect(page.getByRole('heading',{level:1,name:'Articulación, dinámica y grados de certeza'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByRole('heading',{name:'HECHO VERIFICADO'})).toBeVisible(); await expect(a.getByRole('heading',{name:'HIPÓTESIS DE ESCUCHA'})).toBeVisible(); await expect(a.getByText(/no demuestra que el intérprete original/i)).toBeVisible(); });

test('F6 U2 L4 verifies without turning external material into automatic authority', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-6-unidad-2/contrastar-corregir-y-documentar/'); await expect(page.getByRole('heading',{level:1,name:'Contrastar, corregir y documentar'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/No todas las fuentes tienen la misma autoridad para todas las preguntas/i)).toBeVisible(); await expect(a.getByText(/VERSIÓN ANTERIOR → EVIDENCIA NUEVA → CAMBIO → CONFIANZA ACTUAL/i)).toBeVisible(); });

test('F6 U2 Checkpoint 6A certifies E6 minimum without claiming Hito 7', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-6-unidad-2/checkpoint-transcripcion-funcional/'); await expect(page.getByRole('heading',{level:1,name:'Checkpoint 6A — Transcripción funcional'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/E6 MÍNIMO en una tarea preparada/i)).toBeVisible(); await expect(a.getByText(/E6 FUNCIONAL en cualquier contexto/i)).toBeVisible(); await expect(a.getByText(/Hito 7 — Aprendiz autónomo/i)).toBeVisible(); await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible(); });
