import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }

test('F5 U12 overview preserves Hito 6 and the three-piece evidence model', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-12/'); await expect(page.getByRole('heading',{level:1,name:'Integración y Hito 6'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/Interpretar varias piezas completas de dificultad adecuada manteniendo estructura, tiempo, dinámica y recuperación ante errores/i).first()).toBeVisible(); await expect(a.getByText(/tres piezas completas de dificultad adecuada/i).first()).toBeVisible(); await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible(); });

test('F5 U12 L2 keeps Piece A and Piece B as different learning routes and feels', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-12/piezas-a-b-dos-rutas/'); await expect(page.getByRole('heading',{level:1,name:'Pieza A + Pieza B: dos rutas, dos familias'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/USAR CHART ≠ NO SABER LA PIEZA/i)).toBeVisible(); await expect(a.getByText(/SHUFFLE ≠ CORCHEAS RECTAS CON OTRO NOMBRE/i)).toBeVisible(); await expect(a.getByText(/BACKBEAT BINARIO ↔ SHUFFLE \/ SUBDIVISIÓN TERNARIA/i)).toBeVisible(); });

test('F5 U12 L4 uses a qualitative portfolio and explicit decisions', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-12/portfolio-recuperacion-decision/'); await expect(page.getByRole('heading',{level:1,name:'Portfolio final: comparar, corregir y decidir'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/PORTFOLIO ≠ MEDIA NUMÉRICA DE TRES TOMAS/i)).toBeVisible(); await expect(a.getByText(/UNA DEBILIDAD CRÍTICA SE DIAGNOSTICA/i)).toBeVisible(); await expect(a.getByRole('heading',{name:'AVANZAR'})).toBeVisible(); await expect(a.getByRole('heading',{name:'REDUCIR CARGA'})).toBeVisible(); });

test('F5 U12 final checkpoint states the literal Hito 6 without perfection or BPM gates', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-12/hito-6-baterista-funcional/'); await expect(page.getByRole('heading',{level:1,name:'Hito 6 — Baterista funcional'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/Interpretar varias piezas completas de dificultad adecuada manteniendo estructura, tiempo, dinámica y recuperación ante errores/i).first()).toBeVisible(); await expect(a.getByText(/TRES PIEZAS ES UNA DECISIÓN CURRICULAR DE ESTE CURSO/i)).toBeVisible(); await expect(a.getByText(/RECUPERACIÓN ANTE ERRORES ES PARTE DEL HITO/i)).toBeVisible(); await expect(a.getByText(/No existe BPM de aprobado/i)).toBeVisible(); });
