import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }
async function scoreReady(page:Page){ const score=page.locator('article.course-article [data-notation-score]'); await expect(score).toHaveCount(1); await expect(score.locator('.course-score__status')).toHaveText('Partitura renderizada',{timeout:20_000}); await expect(score.getByRole('button',{name:'Reproducir partitura'})).toBeEnabled(); }

test('F5 U10 overview separates odd meter from grouping in 4/4', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-10/'); await expect(page.getByRole('heading',{level:1,name:'Fusion/progressive: métrica, agrupación y transferencia consciente'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/COMPÁS IRREGULAR ≠ AGRUPACIÓN ASIMÉTRICA EN 4\/4/i)).toBeVisible(); await expect(a.getByText(/AGRUPACIÓN ≠ TUPLET/i)).toBeVisible(); });

test('F5 U10 L1 renders the original 4/4 versus 7/8 comparison', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-10/metrica-vs-agrupacion/'); await expect(page.getByRole('heading',{level:1,name:'Métrica ≠ agrupación: 4/4 (3+3+2) frente a 7/8 (2+2+3)'})).toBeVisible(); await scoreReady(page); await expect(page.locator('article.course-article').getByText(/AGRUPAR DISTINTO NO CAMBIA AUTOMÁTICAMENTE EL COMPÁS/i)).toBeVisible(); });

test('F5 U10 L4 prioritizes fill return and diagnostic separation', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-10/fill-retorno-complejidad/'); await expect(page.getByRole('heading',{level:1,name:'Fill y retorno: complejidad métrica vs. coordinativa'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/COMPLEJIDAD MÉTRICA ≠ COMPLEJIDAD COORDINATIVA/i)).toBeVisible(); await expect(a.getByText(/FILL FUNCIONAL = FRASE \+ RETORNO/i)).toBeVisible(); });
