import { expect, test, type Page, type TestInfo } from '@playwright/test';
const username=process.env.E2E_USERNAME ?? 'e2e-admin'; const password=process.env.E2E_PASSWORD ?? 'ci-e2e-password-2026'; const baseUrl=process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:4323';
async function login(page:Page,testInfo:TestInfo){ if(testInfo.project.name==='webkit-tablet'){ const response=await page.request.post(`${baseUrl}/api/auth/login/`,{form:{username,password},headers:{Origin:baseUrl},maxRedirects:0}); expect(response.status()).toBe(303); const match=/(?:^|,\s*)aprendo_session=([^;]+)/i.exec(response.headers()['set-cookie']??''); expect(match?.[1]).toBeTruthy(); const url=new URL(baseUrl); await page.context().addCookies([{name:'aprendo_session',value:match![1],domain:url.hostname,path:'/',httpOnly:true,secure:false,sameSite:'Strict'}]); return;} await page.goto('/login/'); await page.getByLabel('Usuario').fill(username); await page.getByLabel('Contraseña').fill(password); await page.getByLabel('Contraseña').press('Enter'); await expect(page).toHaveURL(`${baseUrl}/`); }
async function scoreReady(page:Page){ const score=page.locator('article.course-article [data-notation-score]'); await expect(score).toHaveCount(1); await expect(score.locator('.course-score__status')).toHaveText('Partitura renderizada',{timeout:20_000}); await expect(score.getByRole('button',{name:'Reproducir partitura'})).toBeEnabled(); }

test('F5 U8 overview exposes swing and comping boundaries', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-8/'); await expect(page.getByRole('heading',{level:1,name:'Swing, time, comping y navegación jazz'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/REJILLA TERNARIA ≠ SWING REAL COMPLETO/i)).toBeVisible(); await expect(a.getByText(/COMPING ≠ TOCAR MÁS/i)).toBeVisible(); });

test('F5 U8 L1 renders original jazz time model', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-8/ride-swing-time/'); await expect(page.getByRole('heading',{level:1,name:'Ride y swing: construir time sin congelar el feel'})).toBeVisible(); await scoreReady(page); await expect(page.locator('article.course-article').getByText(/REJILLA TERNARIA ≠ SWING REAL COMPLETO/i)).toBeVisible(); });

test('F5 U8 L4 prioritizes form over comping detail', async({page},testInfo)=>{ await login(page,testInfo); await page.goto('/bateria/fase-5-unidad-8/navegacion-forma-jazz/'); await expect(page.getByRole('heading',{level:1,name:'Navegación jazz: forma, cues y continuidad'})).toBeVisible(); const a=page.locator('article.course-article'); await expect(a.getByText(/FORMA CONSERVADA > RESPUESTA PERFECTA/i)).toBeVisible(); await expect(a.getByText(/A — A — B — A/i)).toBeVisible(); });
