#!/usr/bin/env python3
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

DOMAIN = "aprendo.molacomer.com"
MANAGED_START = "    # BEGIN APRENDO APP AUTH"
MANAGED_END = "    # END APRENDO APP AUTH"
PROXY_BODY = """proxy_pass http://127.0.0.1:4321;
proxy_http_version 1.1;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;"""


def matching_brace(text: str, open_brace: int) -> int:
    depth = 0
    for index in range(open_brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise RuntimeError("Unbalanced Nginx braces")


def find_server_block(text: str) -> tuple[int, int]:
    candidates: list[tuple[int, int, str]] = []
    for match in re.finditer(r"(?m)^\s*server\s*\{", text):
        open_brace = text.find("{", match.start(), match.end())
        close_brace = matching_brace(text, open_brace)
        block = text[match.start(): close_brace + 1]
        if re.search(rf"(?m)^\s*server_name\s+[^;]*\b{re.escape(DOMAIN)}\b[^;]*;", block):
            candidates.append((match.start(), close_brace + 1, block))

    if not candidates:
        raise RuntimeError(f"No server block found for {DOMAIN}")

    for start, end, block in candidates:
        if re.search(r"(?m)^\s*listen\s+[^;]*\b443\b[^;]*;", block):
            return start, end

    for start, end, block in candidates:
        if re.search(r"(?m)^\s*ssl\s+on\s*;", block):
            return start, end

    raise RuntimeError(f"No HTTPS server block found for {DOMAIN}")


def proxy_lines(indent: str) -> str:
    return "\n".join(f"{indent}{line}" for line in PROXY_BODY.splitlines())


def managed_locations() -> str:
    return f"""
{MANAGED_START}
    location = /__aprendo_session_check {{
        internal;
        proxy_pass http://127.0.0.1:4321/api/auth/check/;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Host $host;
        proxy_set_header X-Original-URI $request_uri;
    }}

    location @aprendo_login_redirect {{
        return 303 /login/;
    }}

    location = /login {{
{proxy_lines('        ')}
    }}

    location = /login/ {{
{proxy_lines('        ')}
    }}

    # Login CSS/JS generated by Astro must remain reachable before authentication.
    location ^~ /_astro/ {{
{proxy_lines('        ')}
    }}
{MANAGED_END}
"""


def configure_server_block(block: str) -> str:
    # Once the managed v1 block is present the transform is already complete.
    # This keeps routine deploys byte-for-byte idempotent.
    if MANAGED_START in block and MANAGED_END in block:
        return block

    block = re.sub(
        r"(?m)^\s*auth_basic(?:_user_file)?\s+[^;]*;\s*\n?",
        "",
        block,
    )

    server_open = block.find("{")
    if server_open < 0:
        raise RuntimeError("Invalid server block")
    block = block[:server_open + 1] + "\n    auth_basic off;" + block[server_open + 1:]

    location = re.search(r"(?m)^(?P<indent>\s*)location\s+/\s*\{", block)
    protected_body = (
        "auth_request /__aprendo_session_check;\n"
        "error_page 401 = @aprendo_login_redirect;\n"
        + PROXY_BODY
    )
    if location:
        open_brace = block.find("{", location.start(), location.end())
        close_brace = matching_brace(block, open_brace)
        indent = location.group("indent")
        body_indent = indent + "    "
        replacement = (
            f"{indent}location / {{\n"
            + "\n".join(f"{body_indent}{line}" for line in protected_body.splitlines())
            + f"\n{indent}}}"
        )
        block = block[:location.start()] + replacement + block[close_brace + 1:]
    else:
        closing = block.rfind("}")
        indent = "    "
        body_indent = indent + "    "
        location_block = (
            f"\n{indent}location / {{\n"
            + "\n".join(f"{body_indent}{line}" for line in protected_body.splitlines())
            + f"\n{indent}}}\n"
        )
        block = block[:closing] + location_block + block[closing:]

    closing = block.rfind("}")
    return block[:closing] + managed_locations() + block[closing:]


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: configure-nginx-app-auth.py /path/to/nginx/site.conf")

    path = Path(sys.argv[1])
    text = path.read_text()
    start, end = find_server_block(text)
    updated = text[:start] + configure_server_block(text[start:end]) + text[end:]
    if updated == text:
        return

    backup = path.with_name(path.name + ".pre-aprendo-app-auth")
    if not backup.exists():
        shutil.copy2(path, backup)
    path.write_text(updated)


if __name__ == "__main__":
    main()
