name: Generate npm lockfile

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Generate lockfile
        run: npm install --no-audit --no-fund

      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
          if-no-files-found: error
